---
env:
  browser: true
  es6: true
  node: true
extends:
  - plugin:react/recommended
  - andrewaylett
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  impliedStrict: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  jest/no-deprecated-functions: 0
  '@typescript-eslint/no-var-requires': 0
settings:
  react:
    version: detect
  linkComponents:
    - name: Link
      linkAttribute: to
