image: node:12

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - npm ci

include:
  - template: Dependency-Scanning.gitlab-ci.yml

pages:
  stage: deploy
  script:
  - ./node_modules/.bin/gatsby build
  artifacts:
    paths:
    - public
  only:
  - master
